Handle eth_signTypedData RPC call
LedgerHQ/eth-dapp-browser pull request #12
Opened 2022-08-11 11:50 UTC by chabroA

Handle eth_signTypedData RPC call

2022-08-11 16:13 UTC, Justkant approved these changes

2022-08-12 12:36 UTC, sprohaszka-ledger approved these changes

2022-11-03 09:47 UTC, chabroA commented
TODO: update sdk `signMessage` usage (signature of function has changed since PR date)

2022-11-15 09:36 UTC, Justkant requested changes
Update the review so we don't forget about that

2022-11-15 09:36 UTC, Justkant commented on src/DAPPBrowser/index.tsx
> +                  Buffer.from(message)
```suggestion
                  Buffer.from(message, "hex")
```

2022-11-17 13:46 UTC, Justkant commented on src/DAPPBrowser/index.tsx
> +                  Buffer.from(message)
My bad on that it's actually correct like that because you expect message to be a stringified object and not an hex message

2022-11-17 13:47 UTC, Justkant approved these changes
My bad on the request changes, it's actually correct like that because you expect message to be a stringified object and not an hex message

2022-11-17 19:35 UTC, merged